spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market-app
    username: market-app
    password: market-app
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
